# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github

repository:
  name: orchidarium
  description: An extensible environmental control platform for maintaining atmospheric conditions in closed or confined spaces, terrariums, and aquariums.
  homepage: https://tiger-lily-plants.com
  private: false
  topics: orchids, terrarium, sensors, python

branches:
  - name: master
    protection:
      required_status_checks:
        strict: true
        contexts: []
          # - dynamic-continuation

      restrictions:
        users: []
        apps: []
        teams: []